// Code generated by tools/generate_ownership_contract.py; DO NOT EDIT.
// Canonical source: server/payments/ownership.py.
package client

const OwnershipPurpose = "SECONDED: prove this wallet paid for this check"
const OwnershipValiditySeconds = 600
